% (C) Copyright 2021 Remi Gau

function PlotMainProfile(GroupMean, LowerError, UpperError, Opt, xOffset, iColumn, iLine)
    %
    % Plots the laminar profile for BOLD or MVPA
    %

    ProfileLine = SetProfileLineParameters();

    if exist('iLine', 'var') && ~isempty(iLine)
        ProfileLine.MarkerFaceColor = Opt.Specific{1, iColumn}.LineColors(iLine, :);
        ProfileLine.LineColor = Opt.Specific{1, iColumn}.LineColors(iLine, :);
    end

    xPosition = (1:Opt.NbLayers) + xOffset;

    if Opt.ShadedErrorBar
        shadedErrorBar( ...
                       xPosition, ...
                       GroupMean, ...
                       [LowerError; UpperError], ...
                       'lineProps', { ...
                                     'Marker', ProfileLine.Marker, ...
                                     'MarkerSize', ProfileLine.MarkerSize, ...
                                     'MarkerFaceColor', ProfileLine.MarkerFaceColor, ...
                                     'LineStyle', ProfileLine.LineStyle, ...
                                     'LineWidth', ProfileLine.LineWidth, ...
                                     'Color', ProfileLine.LineColor}, ...
                       'transparent', ProfileLine.Transparent);

    else

        % Plots a thin error bar and a thick line across data points
        l = errorbar( ...
                     xPosition, ...
                     GroupMean, ...
                     LowerError, ...
                     UpperError);

        set(l, ...
            'Marker', ProfileLine.Marker, ...
            'MarkerSize', ProfileLine.MarkerSize, ...
            'MarkerFaceColor', ProfileLine.MarkerFaceColor, ...
            'LineStyle', ProfileLine.LineStyle, ...
            'Color', ProfileLine.LineColor, ...
            'LineWidth', ProfileLine.ErrorLineWidth);

        l = plot( ...
                 xPosition, ...
                 GroupMean);

        set(l, ...
            'Marker', ProfileLine.Marker, ...
            'MarkerSize', ProfileLine.MarkerSize, ...
            'MarkerFaceColor', ProfileLine.MarkerFaceColor, ...
            'LineStyle', ProfileLine.LineStyle, ...
            'LineWidth', ProfileLine.LineWidth, ...
            'Color', ProfileLine.LineColor);

    end
end
