name: tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches: '*'

env:
  CODECOV_TOKEN: 7e8d534a-aa5f-4163-9526-e2dcfef6b99b
  OCTFLAGS: --no-gui --no-window-system --silent

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y install octave liboctave-dev
        sudo apt-get -y install nodejs npm

    - name: Clone repo
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2

    - name: Install Moxunit and MOcov
      run: |
        git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
        make -C MOxUnit install
        git clone https://github.com/MOcov/MOcov.git --depth 1
        make -C MOcov install

    - name: Update octave path
      run: |
        octave $OCTFLAGS --eval "InitLaminarTools; savepath();"

    - name: Run tests
      run: |
        octave $OCTFLAGS --eval "runTests"
        cat test_report.log | grep 0
        bash <(curl -s https://codecov.io/bash)

